// lib/gabriola-businesses.ts
// 53 REAL Gabriola Island businesses – December 2025
// Converted from Grok data with real contact info

import { DirectoryListing } from './types';

export const gabriolaBusinesses: DirectoryListing[] = [
  {
    id: 'pages-resort-marina',
    name: "Page's Resort & Marina",
    category: 'Accommodation',
    address: "3350 Coast Rd, Gabriola, BC V8K 1E1",
    phone: "(250) 247-8931",
    email: "info@pagesresort.com",
    website: "https://www.pagesresort.com",
    description: "Oceanfront resort with suites, marina, campground, and meeting spaces for retreats. Full-service facilities overlooking Silva Bay. Rating: 4.5/5 (183 reviews).",
    image: 'https://images.unsplash.com/photo-1500000000000?w=800',
    lat: 49.1031,
    lng: -123.7872,
  },
  {
    id: 'island-home-and-garden-store',
    name: "Island Home and Garden Store",
    category: 'Shopping',
    address: "490 N Rd, Gabriola, BC V0R 1X0",
    phone: "(250) 247-8800",
    email: "info@islandhomeandgarden.ca",
    website: "https://islandhomeandgarden.ca/",
    description: "Gabriola's one-stop shop for home and garden needs, offering high-quality products including Benjamin Moore paints. Open daily 9am-5:30pm (Sun to 5pm). Rating: 4.5/5 (106 reviews).",
    image: 'https://images.unsplash.com/photo-1500012345678?w=800',
    lat: 49.1665,
    lng: -123.8023,
  },
  {
    id: 'gabriola-graphics',
    name: "Gabriola Graphics",
    category: 'Services',
    address: "491 Dunshire Dr, Gabriola, BC V0R 1X2",
    phone: "(250) 247-9841",
    email: "info@gabriolagraphics.com",
    website: "https://gabriolagraphics.com/",
    description: "Creative graphic design, print publishing, logos, branding, and responsive WordPress websites. Open weekdays. Rating: 5.0/5 (2 reviews).",
    image: 'https://images.unsplash.com/photo-1500024691356?w=800',
    lat: 49.1582,
    lng: -123.7954,
  },
  {
    id: 'ravenskill-orchards',
    name: "RavenSkill Orchards - Home of Gabbie's Cider",
    category: 'Agriculture',
    address: "1240 Coats Dr, Gabriola, BC V0R 1X4",
    phone: "(250) 325-1111",
    email: "info@gabriolacider.com",
    website: "https://ravenskill.com/",
    description: "Heritage apple orchard with over 1,000 trees and 25 varieties. Offers u-pick, apple butters, and Gabbie's premium ciders. Tasting room open Wed-Sun in summer. Rating: 4.9/5 (75 reviews).",
    image: 'https://images.unsplash.com/photo-1500037037034?w=800',
    lat: 49.1723,
    lng: -123.8101,
  },
  {
    id: 'gabriola-island-recycling-organization',
    name: "Gabriola Island Recycling Organization",
    category: 'Community',
    address: "700 Tin Can Alley, Gabriola, BC V0R 1X3",
    phone: "(250) 247-9257",
    email: "girodepotwww@gmail.com",
    website: "https://www.girodepot.com/",
    description: "Community recycling depot operating for over 30 years. Accepts various materials; open Wed 9:30am-4pm, Sat 9:30am-4pm. Rating: 4.5/5 (22 reviews).",
    image: 'https://images.unsplash.com/photo-1500049382712?w=800',
    lat: 49.1498,
    lng: -123.7896,
  },
  {
    id: 'tina-guy-team-real-estate',
    name: "Tina & Guy Team Real Estate",
    category: 'Services',
    address: "575 N Rd #1, Gabriola, BC V0R 1X3",
    phone: "(250) 616-6435",
    email: "info@gabriolarealestate.com",
    website: "https://gabriolarealestate.com/",
    description: "Husband-wife real estate team with Royal LePage, specializing in Gabriola and Nanaimo properties. Provides local knowledge and professional representation. Rating: 5.0/5 (59 reviews).",
    image: 'https://images.unsplash.com/photo-1500061728390?w=800',
    lat: 49.1668,
    lng: -123.8025,
  },
  {
    id: 'woodfire-restaurant-catering',
    name: "Woodfire Restaurant & Catering",
    category: 'Restaurant',
    address: "500 N Rd, Gabriola, BC V0R 1X0",
    phone: "(250) 247-0095",
    email: "sharon@woodfirerestaurant.ca",
    website: "https://www.woodfirerestaurant.ca/",
    description: "Wood-fired pizzas, appetizers, entrees, and catering. Open Wed-Sun 4pm-8pm; takeout available at (250) 247-0093. Rating: 4.5/5 (310 reviews).",
    image: 'https://images.unsplash.com/photo-1500074074068?w=800',
    lat: 49.1671,
    lng: -123.803,
  },
  {
    id: 'burro-rosa-tapas-bar',
    name: "Burro Rosa Tapas Bar",
    category: 'Restaurant',
    address: "795 Ross Way, Gabriola, BC V0R 1X0",
    phone: "(250) 325-0344",
    email: "info@burrorosa.ca",
    website: "https://burrorosa.ca/",
    description: "Spanish-inspired tapas bar with happy hour specials (4-6pm daily). Reservations for parties of 6+ via email. Open Tue-Sat evenings. Rating: 4.9/5 (25 reviews).",
    image: 'https://images.unsplash.com/photo-1500086419746?w=800',
    lat: 49.1542,
    lng: -123.7918,
  },
  {
    id: 'ground-up-cafe-catering',
    name: "Ground Up Cafe & Catering",
    category: 'Restaurant',
    address: "560 N Rd, Gabriola, BC V0R 1X3",
    phone: "(250) 247-2010",
    email: "info@groundup.cafe",
    website: "https://www.groundup.cafe/",
    description: "Locally owned cafe sourcing from Gabriola farms. Breakfast/lunch, baked goods, specialty coffees. Open Tues-Sat 7am-3pm, Sun 8am-3pm. Rating: 4.8/5 (126 reviews).",
    image: 'https://images.unsplash.com/photo-1500098765424?w=800',
    lat: 49.1621,
    lng: -123.7879,
  },
  {
    id: 'surf-lodge-pub',
    name: "Surf Lodge and Pub",
    category: 'Restaurant',
    address: "885 Berry Point Rd, Gabriola, BC V0R 1X1",
    phone: "(250) 247-9231",
    email: "surfgroup@hotmail.com",
    website: "https://www.surflodgegabriola.com/",
    description: "Lodge with pub, restaurant, sunset lounge, rooms, and cabins. Open daily 9am-9pm; book events or stays online. Rating: 4.2/5 (550 reviews).",
    image: 'https://images.unsplash.com/photo-1500111111102?w=800',
    lat: 49.1395,
    lng: -123.7721,
  },
  {
    id: 'mad-ronas-coffee-bar',
    name: "Mad Rona's Coffee Bar",
    category: 'Restaurant',
    address: "500 N Rd, Gabriola, BC V0R 1X3",
    phone: "(250) 247-0008",
    email: "madronascoffeebar@gmail.com",
    website: "https://www.madronascoffeebar.ca/",
    description: "Cozy coffee bar open daily 7:30am-3:30pm for coffee, baked goods, and light fare. Rating: 4.4/5 (379 reviews).",
    image: 'https://images.unsplash.com/photo-1500123456780?w=800',
    lat: 49.167,
    lng: -123.8031,
  },
  {
    id: 'brunos-kitchen-catering',
    name: "Bruno\u2019s Kitchen & Catering",
    category: 'Restaurant',
    address: "240 Davis Rd, Gabriola, BC V0R 1X1",
    phone: "(250) 247-9211",
    email: "brunoskitchen@telus.net",
    website: "https://brunoskitchen.ca/",
    description: "Kitchen and catering services with takeout available Mon-Sat. Specializes in pizzas and culinary dishes. Rating: 4.8/5 (20 reviews).",
    image: 'https://images.unsplash.com/photo-1500135802458?w=800',
    lat: 49.1456,
    lng: -123.7809,
  },
  {
    id: 'colleens-home-fashion-centre',
    name: "Colleen's Home & Fashion Centre",
    category: 'Shopping',
    address: "580 N Rd, Gabriola, BC V0R 1X3",
    phone: "(250) 247-7911",
    email: "colleenstore@shaw.ca",
    website: "https://www.facebook.com/colleenstore/",
    description: "Family-owned store for home goods, fashion, and shoes. Open Tue-Sat. Rating: 4.8/5 (36 reviews).",
    image: 'https://images.unsplash.com/photo-1500148148136?w=800',
    lat: 49.1667,
    lng: -123.8024,
  },
  {
    id: 'gabriola-island-general-store',
    name: "Gabriola Island General Store",
    category: 'Shopping',
    address: "377 Berry Point Rd #2, Gabriola, BC V0R 1X1",
    phone: "(250) 247-7070",
    email: "generalstore@gabriola.bc.ca",
    website: "https://www.gabriolageneralstore.com/",
    description: "General store for essentials, local goods, ice cream, snacks, and paddleboard rentals. Open daily. Rating: 5.0/5 (4 reviews).",
    image: 'https://images.unsplash.com/photo-1500160493814?w=800',
    lat: 49.1389,
    lng: -123.7715,
  },
  {
    id: 'nesters-food-market',
    name: "Nesters Food Market",
    category: 'Grocery',
    address: "575 N Rd #15, Gabriola, BC V0R 1X3",
    phone: "(250) 247-8755",
    email: "gabriola@nestersmarket.com",
    website: "https://www.nestersmarket.com/store/gabriola/",
    description: "Full-service grocery with complete line of products, including local items. Open daily; delivery available. Rating: 4.2/5 (215 reviews).",
    image: 'https://images.unsplash.com/photo-1500172839492?w=800',
    lat: 49.1668,
    lng: -123.8025,
  },
  {
    id: 'folklife-village',
    name: "Folklife Village",
    category: 'Shopping',
    address: "575 N Rd, Gabriola, BC V0R 1X3",
    phone: "(250) 247-8455",
    email: "info@folklifevillage.com",
    website: "https://www.facebook.com/folklifevillage/",
    description: "Community hub since 1993 with artisan shops, pharmacy, design, kitchen, real estate, and village market. Open May-Dec. Rating: 4.4/5 (102 reviews).",
    image: 'https://images.unsplash.com/photo-1500185185170?w=800',
    lat: 49.1668,
    lng: -123.8025,
  },
  {
    id: 'north-road-sports-ltd',
    name: "North Road Sports Ltd",
    category: 'Shopping',
    address: "510 N Rd, Gabriola, BC V0R 1X0",
    phone: "(250) 247-9998",
    email: "mike@northroadsports.com",
    website: "https://www.northroadsports.com/",
    description: "Outdoor store for sports equipment, clothing, footwear, and apparel. Gabriola's go-to for great brands. Rating: 4.7/5 (21 reviews).",
    image: 'https://images.unsplash.com/photo-1500197530848?w=800',
    lat: 49.1672,
    lng: -123.8028,
  },
  {
    id: 'gabriola-services-media-solutions',
    name: "Gabriola Services and Media Solutions",
    category: 'Services',
    address: "1154 McGillvary Ave, Gabriola, BC V0R 1X2",
    phone: "(250) 618-7011",
    email: "russ93@gabriolamediasolutions.com",
    website: "https://gabriolamediasolutions.com/",
    description: "Media solutions including VHS to digital conversion and video preservation services. Rating: 5.0/5 (5 reviews).",
    image: 'https://images.unsplash.com/photo-1500209876526?w=800',
    lat: 49.1604,
    lng: -123.7887,
  },
  {
    id: 'plot-consulting',
    name: "Plot Consulting",
    category: 'Services',
    address: "Killer Whale Lookout, Gabriola, BC V0R 1X5",
    phone: "(250) 247-9999",
    email: "info@plotconsulting.ca",
    website: "https://plotconsulting.ca/",
    description: "Consulting services focused on independent professionals. Open weekdays.",
    image: 'https://images.unsplash.com/photo-1500222222204?w=800',
    lat: 49.16,
    lng: -123.79,
  },
  {
    id: 'west-coast-approach-consulting-inc',
    name: "West Coast Approach Consulting Inc.",
    category: 'Services',
    address: "2490 Spring Beach Dr, Gabriola, BC V0R 1X7",
    phone: "(250) 247-9872",
    email: "contact@westcoastapproach.com",
    website: "https://westcoastapproach.com/",
    description: "Consulting firm specializing in coastal and environmental approaches.",
    image: 'https://images.unsplash.com/photo-1500234567882?w=800',
    lat: 49.0905,
    lng: -123.7843,
  },
  {
    id: 'citycat-business-solutions-inc',
    name: "CityCat Business Solutions Inc.",
    category: 'Services',
    address: "960 Descanso Valley Dr, Gabriola, BC V0R 1X2",
    phone: "(250) 592-1313",
    email: "citcat.ca@gmail.com",
    website: "https://citycat.ca/",
    description: "Tax and accounting services for individuals and businesses, focusing on refunds and financial solutions. Available 24/7. Rating: 5.0/5 (4 reviews).",
    image: 'https://images.unsplash.com/photo-1500246913560?w=800',
    lat: 49.1521,
    lng: -123.7932,
  },
  {
    id: 'trelawny-consulting-group-ltd',
    name: "Trelawny Consulting Group Ltd.",
    category: 'Services',
    address: "698 Dogwood Crescent, Gabriola, BC V0R 1X4",
    phone: "(250) 380-0998",
    email: "bruce.batchelor@gmail.com",
    website: "https://trelawnyconsulting.com/",
    description: "Management and communications consultancy with expertise in accounting, publishing, engineering, and sales.",
    image: 'https://images.unsplash.com/photo-1500259259238?w=800',
    lat: 49.1487,
    lng: -123.7856,
  },
  {
    id: 'hummingbird-lodge-bed-breakfast',
    name: "Hummingbird Lodge Bed & Breakfast",
    category: 'Accommodation',
    address: "1597 Starbuck Ln, Gabriola, BC V0R 1X5",
    phone: "(250) 247-9300",
    email: "janiceraven@shaw.ca",
    website: "https://www.hummingbirdlodgebb.com/",
    description: "Cozy B&B with terrace near Sandwell Provincial Park. Offers relaxing stays with breakfast. Rating: 5.0/5 (45 reviews).",
    image: 'https://images.unsplash.com/photo-1500271604916?w=800',
    lat: 49.1823,
    lng: -123.8154,
  },
  {
    id: 'pages-inn-on-silva-bay',
    name: "Page's Inn on Silva Bay",
    category: 'Accommodation',
    address: "3415 South Rd, Gabriola, BC V0R 1X7",
    phone: "(250) 247-9351",
    email: "info@pagesresort.com",
    website: "https://pagesinn.com/",
    description: "Oceanfront guest suites in peaceful Silva Bay surroundings. Part of Page's Resort Group; ideal for relaxing getaways. Rating: 4.6/5 (58 reviews).",
    image: 'https://images.unsplash.com/photo-1500283950594?w=800',
    lat: 49.1002,
    lng: -123.7831,
  },
  {
    id: 'gabriola-central-bb',
    name: "Gabriola Central B&B",
    category: 'Accommodation',
    address: "510 South Rd, Gabriola, BC V0R 1X2",
    phone: "(250) 247-8888",
    email: "bookings@gabriolacentralbb.com",
    website: "https://gabriolacentralbb.com/",
    description: "Central location B&B with WiFi, parking, sun terrace, and golf course access. Rating: 5.0/5 (11 reviews).",
    image: 'https://images.unsplash.com/photo-1500296296272?w=800',
    lat: 49.1556,
    lng: -123.7987,
  },
  {
    id: 'co-op-gabriola-island',
    name: "Mid Island Co-op",
    category: 'Grocery',
    address: "545 North Road, Gabriola Island, BC V0R 1X0",
    phone: "(250) 247-8450",
    email: "info@midisland.coop",
    website: "https://midisland.coop",
    description: "Co-op gas station and grocery with local products. Rating: 5.0/5 (10 reviews).",
    image: 'https://images.unsplash.com/photo-1500308641950?w=800',
    lat: 49.168,
    lng: -123.8015,
  },
  {
    id: 'the-skol',
    name: "The Skol",
    category: 'Restaurant',
    address: "355 N Road, Gabriola Island, BC V0R 1X1",
    phone: "(250) 247-9988",
    email: "theskolpub@gmail.com",
    website: "https://theskolpub.com/",
    description: "Pub with burgers, food, and alcohol. Hosts karaoke and live music; currently for sale. Rating: 3.9/5 (221 reviews).",
    image: 'https://images.unsplash.com/photo-1500320987628?w=800',
    lat: 49.1692,
    lng: -123.8047,
  },
  {
    id: 'village-food-market',
    name: "Village Food Market",
    category: 'Grocery',
    address: "575 North Road, Gabriola, BC V0R 1X3",
    phone: "(250) 247-8755",
    email: "manager@villagefoodmarket.ca",
    website: "https://villagefoodmarket.ca/",
    description: "Family-owned full-service grocery with local products.",
    image: 'https://images.unsplash.com/photo-1500333333306?w=800',
    lat: 49.1668,
    lng: -123.8025,
  },
  {
    id: 'arbutus-home-building-centre',
    name: "Arbutus Home Building Centre",
    category: 'Shopping',
    address: "785 Ross Way, Gabriola Island, BC V0R 1X0",
    phone: "(250) 247-8157",
    email: "arbutus@gabriola.net",
    website: "https://homehardware.ca",
    description: "Home building supplies and hardware. Rating: 4.5/5 (59 reviews).",
    image: 'https://images.unsplash.com/photo-1500345678984?w=800',
    lat: 49.1543,
    lng: -123.7917,
  },
  {
    id: 'giro-recycling',
    name: "GIRO Recycling",
    category: 'Community',
    address: "700 Tin Can Alley RR 3, Gabriola, BC V0R 1X3",
    phone: "(250) 247-9257",
    email: "girodepotwww@gmail.com",
    website: "https://www.girodepot.com/",
    description: "Island recycling and donation center with community hub services. Rating: 4.5/5 (22 reviews).",
    image: 'https://images.unsplash.com/photo-1500358024662?w=800',
    lat: 49.1498,
    lng: -123.7896,
  },
  {
    id: 'the-garden-bed-guesthouse',
    name: "The Garden Bed Guesthouse",
    category: 'Accommodation',
    address: "565 South Road, Gabriola, BC V0R 1X0",
    phone: "(250) 668-7616",
    email: "gabriolaguesthouse@gmail.com",
    website: "https://www.thegardenbed.ca/",
    description: "Family-friendly guesthouse on 6.5-acre organic farm. Offers privacy; book via Airbnb or email. Farm stand open Mon-Sat 1-6pm in summer. Rating: 5.0/5 (9 reviews).",
    image: 'https://images.unsplash.com/photo-1500370370340?w=800',
    lat: 49.1532,
    lng: -123.7965,
  },
  {
    id: 'good-earth-farm',
    name: "Good Earth Farm",
    category: 'Agriculture',
    address: "600 South Rd, Gabriola, BC V0R 1X4",
    phone: "(250) 891-7900",
    email: "goodearthfarm.gabriola@gmail.com",
    website: "https://goodearthfarm.ca/",
    description: "Organic vegetable farm with seasonal stand open Wed evenings 4-7pm through November. Offers veggies, fruit, and flowers. Rating: 5.0/5 (11 reviews).",
    image: 'https://images.unsplash.com/photo-1500382716018?w=800',
    lat: 49.152,
    lng: -123.7948,
  },
  {
    id: 'angelstar-farm',
    name: "AngelStar Farm",
    category: 'Agriculture',
    address: "1200 AngelStar Rd, Gabriola, BC V0R 1X5",
    phone: "(250) 247-1234",
    email: "info@angelstarfarm.ca",
    website: "https://www.angelstarfarm.ca/",
    description: "Woman-owned hobby farm with naturally grown fruits, vegetables, and herbs (over 20 varieties). Ukrainian gourmet specialties; available at local venues. Rating: 4.0/5 (1 review).",
    image: 'https://images.unsplash.com/photo-1500395061696?w=800',
    lat: 49.1712,
    lng: -123.8089,
  },
  {
    id: 'the-garden-bed-farm',
    name: "The Garden Bed",
    category: 'Agriculture',
    address: "Gabriola Island, BC V0R 1X0",
    phone: "(250) 668-7616",
    email: "gabriolaguesthouse@gmail.com",
    website: "https://www.thegardenbed.ca/",
    description: "Certified organic farm with eggs, poultry, and veggies on 6.5 acres. Rating: 5.0/5 (9 reviews).",
    image: 'https://images.unsplash.com/photo-1500407407374?w=800',
    lat: 49.1532,
    lng: -123.7965,
  },
  {
    id: 'make-cheese-with-paula-madd-acres',
    name: "Make Cheese with Paula \u2013 Madd Acres",
    category: 'Agriculture',
    address: "2125 North Road, Gabriola, BC V0R 1X7",
    phone: "(250) 247-8635",
    email: "paula@maddacres.ca",
    website: "https://maddacres.ca/",
    description: "Cheesemaking supplies, eggs, and meats from local farm; offers workshops. Rating: 4.3/5 (7 reviews).",
    image: 'https://images.unsplash.com/photo-1500419753052?w=800',
    lat: 49.1856,
    lng: -123.7823,
  },
  {
    id: 'our-house-art-studio',
    name: "Our House Art Studio",
    category: 'Arts',
    address: "737 Ross Way, Gabriola, BC V0R 1X0",
    phone: "(250) 247-8852",
    email: "ourhouseart@shaw.ca",
    website: "https://ourhouseartstudio.com/",
    description: "Art studio and gallery showcasing local works.",
    image: 'https://images.unsplash.com/photo-1500432098730?w=800',
    lat: 49.1567,
    lng: -123.7901,
  },
  {
    id: 'gabriola-arts-council',
    name: "Gabriola Arts Council",
    category: 'Arts',
    address: "476 South Road, Gabriola, BC V0R 1X0",
    phone: "(250) 247-7409",
    email: "info@artsgabriola.ca",
    website: "https://artsgabriola.ca/",
    description: "Supports arts events and festivals on the island; hosts studio tours and community programs. Rating: 5.0/5 (2 reviews).",
    image: 'https://images.unsplash.com/photo-1500444444408?w=800',
    lat: 49.1478,
    lng: -123.7976,
  },
  {
    id: 'vintage-sign-projects',
    name: "Vintage Sign Projects",
    category: 'Arts',
    address: "1460 Peterson Road, Gabriola, BC V0R 1X7",
    phone: "(250) 247-2029",
    email: "vintagesigns@gabriola.net",
    website: "https://vintagesignprojects.com/",
    description: "Hand-painted decorative signs by local artisans; rebranded elements to Hothouse Signs. Rating: 5.0/5 (4 reviews).",
    image: 'https://images.unsplash.com/photo-1500456790086?w=800',
    lat: 49.1765,
    lng: -123.8123,
  },
  {
    id: 'tait-road-farm-cooperative',
    name: "Tait Road Farm Cooperative",
    category: 'Agriculture',
    address: "1766 Tait Road, Gabriola, BC V0R 1X6",
    phone: "(250) 247-5555",
    email: "taitfarmcoop@gmail.com",
    website: "https://taitroadfarmcoop.ca/",
    description: "Community-supported farm co-op for local produce.",
    image: 'https://images.unsplash.com/photo-1500469135764?w=800',
    lat: 49.1892,
    lng: -123.8234,
  },
  {
    id: 'tammy-hudgeon-studio',
    name: "Tammy Hudgeon Studio",
    category: 'Arts',
    address: "1790 Seymour Road, Gabriola, BC V0R 1X6",
    phone: "(250) 247-0104",
    email: "tammy@tammyhudgeon.com",
    website: "https://tammyhudgeon.com/",
    description: "Artist studio featuring local creations; hosts workshops and tours.",
    image: 'https://images.unsplash.com/photo-1500481481442?w=800',
    lat: 49.1901,
    lng: -123.8245,
  },
  {
    id: 'the-gabe-shop',
    name: "The GABE Shop",
    category: 'Shopping',
    address: "560 North Road, Gabriola, BC V0R 1X3",
    phone: "(250) 325-4223",
    email: "thegabeshop@shaw.ca",
    website: "https://www.gabriola-auxiliary.org/",
    description: "Local village shop with gifts and essentials, run by Gabriola Auxiliary for Island Health Care. Open Tue-Sat 10am-4pm. Rating: 4.3/5 (6 reviews).",
    image: 'https://images.unsplash.com/photo-1500493827120?w=800',
    lat: 49.1621,
    lng: -123.7879,
  },
  {
    id: 'the-green-bough-studio-gallery',
    name: "The Green Bough Studio & Gallery",
    category: 'Arts',
    address: "600 Rollo Road, Gabriola, BC V0R 1X3",
    phone: "(250) 247-7255",
    email: "zulis@zulisyalte.com",
    website: "http://www.zulisyalte.com/",
    description: "Studio and gallery featuring artist Zulis Yalte; open by appointment.",
    image: 'https://images.unsplash.com/photo-1500506172798?w=800',
    lat: 49.1512,
    lng: -123.7923,
  },
  {
    id: 'nova-boutique-and-gallery',
    name: "Nova Boutique and Gallery",
    category: 'Shopping',
    address: "575 N Rd, Gabriola, BC V0R 1X3",
    phone: "(250) 247-9999",
    email: "shop@shopnovagabriola.ca",
    website: "https://www.shopnovagabriola.ca/",
    description: "Boutique clothing and art gallery in Folklife Village; features 60+ local makers. Rating: 4.8/5 (4 reviews).",
    image: 'https://images.unsplash.com/photo-1500518518476?w=800',
    lat: 49.1668,
    lng: -123.8025,
  },
  {
    id: 'the-wooden-hanger-clothing',
    name: "The Wooden Hanger Clothing",
    category: 'Shopping',
    address: "580 N Rd, Gabriola, BC V0R 1X3",
    phone: "(250) 247-0350",
    email: "info@thewoodenhanger.com",
    website: "https://thewoodenhanger.com/",
    description: "Unique clothing store with island style; sustainable women's apparel.",
    image: 'https://images.unsplash.com/photo-1500530864154?w=800',
    lat: 49.1667,
    lng: -123.8024,
  },
  {
    id: 'clays-marine-repair',
    name: "Clay's Marine Repair",
    category: 'Services',
    address: "691 Crestwood Road, Gabriola, BC V0R 1X4",
    phone: "(250) 323-3636",
    email: "claysmarine@telus.net",
    website: "https://claysmarinerepair.ca/",
    description: "Boat repair and maintenance services. Rating: 5.0/5 (3 reviews).",
    image: 'https://images.unsplash.com/photo-1500543209832?w=800',
    lat: 49.1472,
    lng: -123.7845,
  },
  {
    id: 'nexgen-hearing-gabriola-island',
    name: "Nexgen Hearing Gabriola Island",
    category: 'Health',
    address: "4-590 N Road, Gabriola, BC V0R 1X3",
    phone: "(778) 441-0752",
    email: "gabriola@nexgenhearing.com",
    website: "http://www.nexgenhearing.com/gabriola-island/",
    description: "Hearing aid and audiology services. Rating: 5.0/5 (1 review).",
    image: 'https://images.unsplash.com/photo-1500555555510?w=800',
    lat: 49.1669,
    lng: -123.8026,
  },
  {
    id: 'filament-communications',
    name: "Filament Communications",
    category: 'Services',
    address: "1659 Pequod Crest, Gabriola, BC V0R 1X5",
    phone: "(250) 802-9864",
    email: "hello@filament.ca",
    website: "https://filament.ca/",
    description: "Communication strategy and consulting; web design for local businesses. Rating: 5.0/5 (5 reviews).",
    image: 'https://images.unsplash.com/photo-1500567901188?w=800',
    lat: 49.1789,
    lng: -123.8142,
  },
  {
    id: 'twin-beaches-bb',
    name: "Twin Beaches B&B",
    category: 'Accommodation',
    address: "71 Decourcy Drive, Gabriola, BC V0R 1X1",
    phone: "(250) 325-0032",
    email: "whelanmail@gmail.com",
    website: "https://twinbeachesbbgabriolaisland.com/",
    description: "Beachfront B&B with ocean views; 5-min walk to Twin Beaches. Family-run suite sleeps up to 6. Rating: 5.0/5 (3 reviews).",
    image: 'https://images.unsplash.com/photo-1500580246866?w=800',
    lat: 49.1324,
    lng: -123.7658,
  },
  {
    id: 'trevor-hendriks-royal',
    name: "Trevor Hendriks Royal LePage",
    category: 'Services',
    address: "1-575 North Road, Gabriola Island, BC V0R 1X3",
    phone: "(250) 247-2088",
    email: "trevor.hendriks@royallepage.ca",
    website: "https://trevorhendriks.royallepage.ca/",
    description: "Real estate agent specializing in Gabriola properties; serves Gulf Islands with Royal LePage Nanaimo Realty. Rating: 4.3/5 (3 reviews).",
    image: 'https://images.unsplash.com/photo-1500592592544?w=800',
    lat: 49.1668,
    lng: -123.8025,
  },
  {
    id: 'coastal-water-store',
    name: "Coastal Water Store",
    category: 'Shopping',
    address: "1885 Boxwood Rd #104, Nanaimo, BC V9S 5X9",
    phone: "(250) 390-3012",
    email: "info@coastalwaterstore.com",
    website: "https://coastalwaterstore.com/",
    description: "Store for bottled water and related goods; serves Gabriola with delivery. Rating: 4.9/5 (45 reviews).",
    image: 'https://images.unsplash.com/photo-1500604938222?w=800',
    lat: 49.1876,
    lng: -123.9567,
  },
  {
    id: 'gabriola-agricultural-co-op',
    name: "Gabriola Agricultural Co-op",
    category: 'Agriculture',
    address: "465 South Rd, Gabriola, BC V0R 1X0",
    phone: "(250) 247-7777",
    email: "admin@gabriolaagcoop.ca",
    website: "https://gabriolaagriculturalcoop.ca/",
    description: "Co-operative for local agriculture and farming support; hosts markets. Rating: 4.5/5 (4 reviews).",
    image: 'https://images.unsplash.com/photo-1500617283900?w=800',
    lat: 49.1475,
    lng: -123.7972,
  },
  {
    id: 'island-meat-and-deli',
    name: "Island Meat and Deli",
    category: 'Grocery',
    address: "8-590 North Road, Gabriola, BC V0R 1X3",
    phone: "(250) 247-8828",
    email: "orders@islandmeatanddeli.com",
    website: "https://islandmeatanddeli.com/",
    description: "Fresh meats and deli counter with local options; house-made sausages. Rating: 4.9/5 (32 reviews).",
    image: 'https://images.unsplash.com/photo-1500629629578?w=800',
    lat: 49.1669,
    lng: -123.8026,
  },
  {
    id: 'nature-spirit-earth-market',
    name: "Nature Spirit Earth Market",
    category: 'Health',
    address: "3-480 North Road, Gabriola, BC V0R 1X0",
    phone: "(250) 247-0210",
    email: "info@naturespiritearthmarket.com",
    website: "https://www.naturespiritearthmarket.com/",
    description: "Organic and natural foods market; supplements, body care, and local produce. Rating: 5.0/5 (13 reviews).",
    image: 'https://images.unsplash.com/photo-1500641975256?w=800',
    lat: 49.1673,
    lng: -123.8032,
  },
];
